steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/webdev-dockers/lostfound-webservice:$COMMIT_SHA', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/webdev-dockers/lostfound-webservice:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'lostfound-webservice'
      - '--image'
      - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/webdev-dockers/lostfound-webservice:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - |
        FIREBASE_API_KEY=${_FIREBASE_API_KEY},\
        FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN},\
        FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},\
        FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET},\
        FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID},\
        FIREBASE_APP_ID=${_FIREBASE_APP_ID},\
        FIRBASE_MEASUREMENT_ID=${_FIRBASE_MEASUREMENT_ID},\
        CLOUDINARY_CLOUD_NAME=${_CLOUDINARY_CLOUD_NAME},\
        CLOUDINARY_API_KEY=${_CLOUDINARY_API_KEY},\
        CLOUDINARY_API_SECRET=${_CLOUDINARY_API_SECRET}
images:
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/webdev-dockers/lostfound-webservice'

substitutions:
  _PROJECT_ID: 'lost-and-found-in-mfu-service'
options:
  logging: CLOUD_LOGGING_ONLY